#os: osx
language: python
python:
#  - "2.7"
#  - "3.5"
  - 3.6

before_install:
  - echo "before install"

install:
  - sudo apt-get update
  # Install Anaconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PKG_NAME=llspy
  - export USER=talley
  - export CONDA_BLD_PATH=~/conda-bld
  - export VERSION=`date +%Y.%m.%d`
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda conda-build
  - conda config --add channels conda-forge
  - conda config --add channels talley
  - conda config --set show_channel_urls true
  - conda info -a


#  - conda build --py 36 -c talley -c conda-forge conda.recipe

#  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib tifffile numba ipython voluptuous watchdog click pyqt pyopencl spimagine raven
#  - source activate test-environment
#  - python setup.py install

script:
  - OUTPUT="$(conda build --py $TRAVIS_PYTHON_VERSION --output conda.recipe)"
  - conda build --py $TRAVIS_PYTHON_VERSION --token $CONDA_UPLOAD_TOKEN --user talley conda.recipe
  - conda convert -p win-64 -p linux-64 -o $CONDA_BLD_PATH $OUTPUT
#  - test $TRAVIS_BRANCH = "master" && bash conda.recipe/conda_upload.sh
