{% set name = "llspy" %}
{% set setupdata = load_setup_py_data() %}

package:
  name: {{ name }}
  {% if environ.get('BRANCH') == "develop" %}
  version: "{{ GIT_DESCRIBE_TAG }}_{{ GIT_BUILD_STR }}"
  {% else %}
  version: {{ setupdata.get('version') }}
  {% endif %}

source:
  # path: ..
  git_url: https://github.com/tlambert03/LLSpy
  git_rev: "{{ environ.get('BRANCH') }}"

build:
  number: 0
  string: 'py{{ PY_VER|replace(".", "") }}_{{ PKG_BUILDNUM }}'
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    {% for key, list in setupdata.get('entry_points').items() %}
      {% for item in list %}
    - {{item}}
      {% endfor %}
    {% endfor %}

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy >=1.0.0
    - tifffile >=0.15.0
    - numba >=0.40
    - voluptuous >=0.11.1
    - watchdog >=0.8.3
    - pyqt >=5.9.2 # [py3k]
    - pyqt >=5.6.0 # [py2k]
    - click >=6.7
    - parse >=1.8.2
    - matplotlib >=2.1.1
    - spimagine >=0.2.6 # [not win]
    - tar ==1.29 # [not win]
    - llspylibs >=0.2.0
    - pathlib2 # [py2k]
    - configparser # [py2k]
    - pigz # [not win]
    - lbzip2 # [not win]
    - sentry-sdk
    - llspy-slm

test:
  requires:
    # - pytest
    # - pytest-qt
    # - llscd
  imports:
    - llspy # [not py2k]
  commands:
    # - which lls  # [unix]
    # - where lls  # [win]
    - lls --help # [not py2k]
    # - lls gui --test # [not linux]
    # - pytest

about:
  home: {{ setupdata.get('url') }}
  license: {{ setupdata.get('license') }}
  license_file: LICENSE
  summary: {{ setupdata.get('description') }}

# app:
#   entry: lls-gui
#   icon: ../_assets/llspy_logo.png
#   summary:  "LLSpy GUI"
