{% set name = "llspy" %}
{% set setupdata = load_setup_py_data() %}
#{% if TRAVIS_BRANCH is defined %}
#{% set branch = TRAVIS_BRANCH %}
#{% else %}
#{% set branch = 'master' %}
#{% endif %}

package:
  name: {{ name }}
  version: {{ setupdata['version'] }}

source:
  #path: ..
  git_url: https://github.com/tlambert03/LLSpy
  git_tag: 'master'

build:
  number: 0
  string: 'py{{ PY_VER|replace(".", "") }}_{{ PKG_BUILDNUM }}'
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    {% for key, list in setupdata['entry_points'].items() %}
      {% for item in list %}
    - {{item}}
      {% endfor %}
    {% endfor %}

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - tifffile
    - numba
    - voluptuous
    - watchdog
    - pyqt >=5
    - click
    - matplotlib
    - spimagine
    - llspylibs
    - pathlib2 # [py2k]
    - configparser # [py2k]
    - pigz
    - lbzip2 # [not win]
    - raven

test:
  imports:
    - llspy # [not py2k]
  commands:
    # - which lls  # [unix]
    # - where lls  # [win]
    - lls --help # [not py2k]
    - lls gui --test # [not linux]
#    - spimagine

about:
  home: {{ setupdata['url'] }}
  license: {{ setupdata['license'] }}
  license_file: LICENSE
  summary: {{ setupdata['description'] }}

# app:
#   entry: lls-gui
#   icon: ../_assets/llspy_logo.png
#   summary:  "LLSpy GUI"
